### ISSUE TITLE
Feature Request: The last task, description and instructions should be cached.

### ISSUE THREAD

**Issue by zenitogr** [gmickel/CodeWhisper#46]
I see that any task I run is not saved somewhere so I can rerun it when it failed

1. run codewhisper task -m llama-3.1-70b-versatile
2. task fails
3. no way of reruning the task
4. you need to type again all the task info

**Comment by gmickel** [comment]
No idea where this feature went ;) I bet CodeWhisper deleted it at some point. Anyway, it's re-implemented now and will be available with 1.7.4
