### ISSUE TITLE
Docs: how to edit the generated Task

### ISSUE THREAD

**Issue by zenitogr** [gmickel/CodeWhisper#47]
for example the task was using pages route for the nextjs app but my app is app route

so in such situation how to make codewhisper regenerate the task with my instructions?

**Comment by gmickel** [comment]
It's strange that it didn't pick up on you using the Next.js app router. If you provided the necessary context, it generally picks up on things like that.

In an empty or nearly empty project, you'll likely need to give it more guidance in your initial task description.

However, to address your question more directly:

CodeWhisper does not have an automatic feedback loop after completing a task. Here's how I use CodeWhisper:

- I write the task almost exactly as I would a feature requirement that a developer implementing it needs to understand. It could also be something else, like a code review or security review.

- CodeWhisper plans the task. I review the plan to ensure it makes sense and make changes if needed.

- CodeWhisper creates a new branch with its changes. I manually review the modifications and adapt them as necessary, just like a code review with a real developer.

**Comment by zenitogr** [comment]
I stated with

I want you to keep in mind these:
-important: this is a 'app route' nextjs project

but I guess llama3.1:70b is the culprit here

**Comment by zenitogr** [comment]
> * CodeWhisper plans the task. I review the plan to ensure it makes sense and make changes if needed.

I really am a bit of a noob dev so that is no me, I reviewed the task and should edit it a bit cause I saw that it was gonna generate a _app.tsx file which is pages route and index.tsx

**Comment by gmickel** [comment]
Yes, Llama 3.1 70B isn't working well for me either. I asked it to update the documentation, but instead it gave me a plan for refactoring CodeWhisper's core. ;)

I added ollama support hoping a local model would follow the instructions well enough, but I'll do more tests.

**Comment by zenitogr** [comment]
maybe when you want for codewhisper to edit the task plan to delete all contents and write your edit instructions? and it goes and edits the task plan it generated initialy?

**Comment by gmickel** [comment]
related #61
