### ISSUE TITLE
I like CodeWhisper maybe have a place for discussion?

### ISSUE THREAD

**Issue by zenitogr** [gmickel/CodeWhisper#50]
like a discord server?

where we can discuss our mileage with models and APIs?

**Comment by gmickel** [comment]
Great idea, I'll make it happen!

**Comment by gmickel** [comment]
Done! Took longer than implementing new features.. ;)

https://discord.com/invite/82mjJkwABQ

**Comment by hashcacher** [comment]
The link here works, but the one in the repo landing page doesn't (capitalization I think)

**Comment by gmickel** [comment]
All 3 links (this one, in the README and in the repository information) work for me 🤔
