### ISSUE TITLE
feature: add an option to start the task workflow from a previously created plan

### ISSUE THREAD

**Issue by hashcacher** [gmickel/CodeWhisper#61]
I love how the problem details are saved, so redoing is faster. 

We can also save the previous

- file context
- plan

so that it's easy to tweak and redo a task when it's not done right the first time.

**Comment by gmickel** [comment]
- Enable logging by default (--log-ai-interactions)
- Extend logging so it store the previously generated plan and selected files/dirs
- Add an option --redo to the task command
- Start the flow from the plan display/editing

I will publish this later, I have a branch with something similar

**Comment by hashcacher** [comment]
Huge! 🎉
