### ISSUE TITLE
Verbose logging

### ISSUE THREAD

**Issue by hashcacher** [gmickel/CodeWhisper#74]
In the proceses of contributing to CodeWhisper, I've run into many errors that get suppressed. It would be helpful to have more verbose logging.

**Comment by hashcacher** [comment]
E.g. a failed call to applyPatch in applyChanges.ts

**Comment by gmickel** [comment]
Totally agree and I'll look into this shortly. In general, most errors should be printed to stdout but I'm sure I missed some.

In the meantime, there is the --log-ai-interactions option which can help diagnose some issues, especially parsing issues.

**Comment by hashcacher** [comment]
Ah that flag wasn't on my radar! Thanks!

**Comment by gmickel** [comment]
Closing in favour of #75
