### ISSUE TITLE
Improve diff mode code modifications

### ISSUE THREAD

**Issue by gmickel** [gmickel/CodeWhisper#84]
Our current implementation only reliably works with Claude 3.5 Sonnet. 

Explore other methods that work reliably with other models.

**Comment by hashcacher** [comment]
With the latest 1.13.5, I was bit confused because I was using claude-3-5-sonnet-20240620, but then I found
`    if (options.diff && modelKey !== 'claude-3-sonnet-20240229') {`

**Comment by gmickel** [comment]
Wow, thanks my ai-assistant... I'll push a quick fix.
